version: '2'

services:
  main_app:
    build:
      dockerfile: Dockerfile
      context: ./bank-app
      target: production
    volumes:
      - .:/usr/src/app
    container_name: bank_app
    restart: on-failure
    env_file:
      - ./bank-app/.env
    
    ports:
        - 3000:3000
    
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bank_app